/** German → French replacements (sorted at runtime by length). */
export const deToFr = [
  ["G.Hub — Digitales Labor", "G.Hub — Laboratoire numérique"],
  ["Ton einschalten", "Activer le son"],
  ["Ton ausschalten", "Désactiver le son"],
  ["Betriebsregister schließen", "Fermer le registre opérationnel"],
  ["G.HUB-MASCHINE WIEDER AKTIVIEREN", "RÉACTIVER LA MACHINE G.HUB"],
  [
    "Alle physischen Kammern wurden in das singuläre Koordinatensystem-Kernsegment gefaltet. Klicken Sie auf den zentralen leuchtenden Sender, um das Labor zu erweitern.",
    "Toutes les chambres physiques ont été repliées dans le segment central du système de coordonnées. Cliquez sur l'émetteur central illuminé pour développer le laboratoire.",
  ],
  ["G.HUB BETRIEBSREGISTER", "REGISTRE OPÉRATIONNEL G.HUB"],
  ["Ein lebendiges Erfindungsstudio", "Un studio d'invention vivant"],
  [
    "Willkommen bei G.Hub — einem hochpräzisen experimentellen digitalen Arbeitsraum an der Schnittstelle von visuellem Design und funktionalem Computing. Diese Plattform verbindet abstrakte Produkte (G.Game, G.Trans) in einer physischen Layout-Schleife.",
    "Bienvenue sur G.Hub — un espace de travail numérique expérimental de haute précision à la frontière du design visuel et de l'informatique fonctionnelle. Cette plateforme connecte des produits abstraits (G.Game, G.Trans) en une boucle de mise en page physique.",
  ],
  ["Mechanische Navigationsanleitung", "Guide de navigation mécanique"],
  [
    "Jog-Dial: Permanent im linken Rand. Drehen oder ziehen, um Kammern auszuwählen.",
    "Jog dial : fixé en permanence dans la marge gauche. Tournez ou faites glisser pour sélectionner les chambres.",
  ],
  ["Mausrad: Überall scrollen, um zwischen Kammern zu wechseln.", "Molette de souris : faites défiler n'importe où pour changer de chambre."],
  [
    "Indikatoren: Codes (L-01 bis L-09) stehen für Kammern im Labor-Machine-Layout.",
    "Indicateurs : les codes (L-01 à L-09) représentent les chambres dans la disposition de la machine du laboratoire.",
  ],
  [
    "Tastatur: Pfeiltasten (oben/unten/links/rechts) für flüssige Navigation.",
    "Clavier : touches fléchées (haut/bas/gauche/droite) pour une navigation fluide.",
  ],
  ["KOGNITIVE BESCHLEUNIGUNG: AKTIV", "ACCÉLÉRATION COGNITIVE : ACTIVE"],
  ["KRISTALLISIERTE SICHERHEIT: GESPERRT", "SÉCURITÉS CRISTALLISÉES : VERROUILLÉES"],
  ["Wo Ideen Wirklichkeit werden", "Là où les idées deviennent réalité"],
  ["Das Zusammenfügen von Gedanken visualisieren", "Visualiser l'assemblage des pensées"],
  ["Das vernetzte neuronale Netz der Ideen", "Le réseau neural connecté des idées"],
  ["Welten schaffen, die es zu erkunden lohnt", "Créer des mondes qui valent la peine d'être explorés"],
  ["Kommunikation jenseits der Sprache", "Communication au-delà de la langue"],
  ["Informationsgesteuerte Prozessmechanik", "Mécanique de processus pilotée par l'information"],
  ["Räumlich montierte kreative Hardware", "Matériel créatif assemblé spatialement"],
  ["Das nächste Experiment beginnt hier", "La prochaine expérience commence ici"],
  ["Koordinatenparameter eingeben", "Entrez vos paramètres de coordonnées"],
  ["DAS LEBENDIGE DIGITALE ERFINDUNGSSTUDIO", "LE STUDIO D'INVENTION NUMÉRIQUE VIVANT"],
  ["Wo Ideen Wirklichkeit werden.", "Là où les idées deviennent réalité."],
  [
    "G.Hub ist ein lebendiges digitales Labor, in dem abstrakte Konzepte kristallisieren. Wir entwerfen, prototypen und bauen taktile Produkte, Kommunikations-Ökosysteme und pixelige Welten.",
    "G.Hub est un laboratoire numérique vivant où les concepts abstraits se cristallisent. Nous concevons, prototypons et construisons des produits tactiles, des écosystèmes de communication et des mondes pixelisés.",
  ],
  ["JOG-DIAL BEDIENEN", "UTILISER LE JOG DIAL"],
  ["DIAL DREHEN, UM NACH INNEN ZU REISEN", "TOURNEZ LE Cadran POUR VOYAGER VERS L'INTÉRIEUR"],
  ["SCROLLRAD UND TOUCH-SWIPE AKTIV", "MOLETTE ET SWIPE TACTILE ACTIVÉS"],
  ["IDEEN-EVOLUTIONS-PIPELINE", "PIPELINE D'ÉVOLUTION DES IDÉES"],
  ["Kristallisierung", "Cristallisation"],
  ["abstrakter Ideenströme.", "des flux d'idées abstraits."],
  [
    "In unserem Labor durchlaufen Gedanken eine strenge automatische Kristallisation. Beobachten Sie, wie Knoten expandieren, Blueprint-Parameter fixieren und Produkte entstehen.",
    "Dans notre laboratoire, les pensées subissent une cristallisation automatique rigoureuse. Observez les nœuds s'étendre, les paramètres de blueprint se verrouiller et les produits émerger.",
  ],
  ["MONTAGETIEFE WÄHLEN:", "SÉLECTIONNEZ LA PROFONDEUR D'ASSEMBLAGE :"],
  ["01. ROHE GEDANKEN", "01. PENSÉES BRUTES"],
  ["02. CAD-SKIZZEN", "02. ESQUISSES CAO"],
  ["03. VEKTOR-SCHEMATA", "03. SCHÉMAS VECTORIELS"],
  ["04. PRODUKTKERN", "04. NOYAU PRODUIT"],
  ["[STUFE KLICKEN, UM LOKALE ANZIEHUNG AUSZULÖSEN]", "[CLIQUEZ SUR L'ÉTAPE POUR DÉCLENCHER LES ATTRACTIONS LOCALES]"],
  ["AUSGEWÄHLTE KAMMER-GATEWAY AKTIVIEREN", "ACTIVER LA PASSERELLE DE LA CHAMBRE SÉLECTIONNÉE"],
  ["G.HUB SYSTEMVERZEICHNIS", "RÉPERTOIRE SYSTÈME G.HUB"],
  ["Zentraler Kern", "Noyau central"],
  [
    "Innovative Spieleentwicklungsplattform, modulare Rendering-Engine und verbundenes Spieler-Ökosystem.",
    "Plateforme de développement de jeux innovante, moteur de rendu modulaire et écosystème de joueurs connectés.",
  ],
  [
    "KI-gestützte mehrsprachige Kommunikationsplattform — Dialekte in Echtzeit über Grenzen hinweg.",
    "Plateforme de communication multilingue alimentée par l'IA — dialectes fluides en temps réel au-delà des frontières.",
  ],
  [
    "Unbekannte Domänen, kinetische Architektursimulationen, räumliche Compute-Engines und KI-Module.",
    "Domaines inexplorés, simulations d'architecture cinétique, moteurs de calcul spatial et modules d'intelligence.",
  ],
  ["SYSTEM-ZENTRALHUB", "HUB CENTRAL SYSTÈME"],
  [
    "Der Zentralkern koordiniert Pipeline-Ausführung, Statusverfolgung und neuronale Datentranslation zwischen Knoten.",
    "Le noyau central coordonne l'exécution du pipeline, le suivi d'état et la traduction des données neuronales entre nœuds.",
  ],
  ["Aktive Routing-Parameter: AKTIV", "Paramètres de routage actifs : ACTIVÉS"],
  ["Telemetrie-Bandbreite: 10 Gb/s", "Bande passante télémétrie inter-nœuds : 10 Gb/s"],
  ["Dezentrale Ledger-Integration: ABGESCHLOSSEN", "Intégration de registre décentralisé : TERMINÉE"],
  ["L-04 KREATIVE UMGEBUNG", "L-04 ENVIRONNEMENT CRÉATIF"],
  [
    "G.Game ist von Grund auf für hyperreaktives Micro-Gaming, prozedurale Welten und Sandbox-Tools konzipiert.",
    "G.Game est conçu dès la base pour le micro-gaming hyper-réactif, les mondes procéduraux et les outils sandbox.",
  ],
  ["Render-Puffer: 120 FPS", "Vitesse du tampon de rendu : 120 FPS"],
  ["Physik: FULL MATRIX COMPUTE", "Paramètres physiques : CALCUL MATRICIEL COMPLET"],
  ["Aktive Nutzer: 142.948 SECURE HUBS", "Utilisateurs actifs : 142 948 HUBS SÉCURISÉS"],
  ["L-05 SPRACH-ENGINE", "L-05 MOTEUR LINGUISTIQUE"],
  [
    "G.Trans übersetzt Intent und kognitive Sprache unter Erhalt von Ton, Kultur und Grammatikrhythmus.",
    "G.Trans traduit l'intention et la parole cognitive en préservant le ton, les références culturelles et le rythme grammatical.",
  ],
  ["Unterstützte Dialekte: 124 FLUID METAS", "Dialectes pris en charge : 124 MÉTA FLUIDES"],
  ["Kognitives Modell: @google/genai core pipeline", "Modèle cognitif : pipeline core @google/genai"],
  ["Transformationsdauer: < 12ms", "Durée de transformation : < 12 ms"],
  ["L-08 NÄCHSTE HORIZONTE", "L-08 PROCHAINS HORIZONS"],
  [
    "Sichere Sandbox für experimentelle Strukturen, autonome Agent-Pods und Multi-User-Umgebungen.",
    "Bac à sable sécurisé hébergeant des structures expérimentales réactives, des pods d'agents autonomes et des environnements multi-utilisateurs.",
  ],
  ["Verfügbare Bandbreite: UNBEGRENZT", "Bande passante disponible : ILLIMITÉE"],
  ["Projektstatus: AKTIVE PROTOTYPEN", "État du projet : PROTOTYPES ACTIFS"],
  ["Systemzustand: EVOLVIEREND", "État du système : EN ÉVOLUTION"],
  ["G.GAME ÖKOSYSTEM // SANDBOX-UMGEBUNG", "ÉCOSYSTÈME G.GAME // ENVIRONNEMENT SANDBOX"],
  ["Welten schaffen,", "Créer des mondes"],
  ["die es zu erkunden lohnt.", "qui valent la peine d'être explorés."],
  [
    "Wir entwickeln einen modularen Spiele-Container, der Mikrophysik, dynamisches Light-Baking und isometrische prozedurale Blöcke vereinfacht.",
    "Nous concevons un conteneur de génération de jeux modulaire simplifiant la micro-physique, le light baking dynamique et les maillages de blocs procéduraux isométriques.",
  ],
  ["VERFÜGBARE KONZEpte:", "APERÇUS DE CONCEPTS DISPONIBLES :"],
  ["01. ISOMETRISCHER TILE-EDITOR", "01. ÉDITEUR DE TUILES ISOMÉTRIQUES"],
  ["Kacheln klicken, um isometrische Würfel zu malen.", "Cliquez sur les tuiles pour peindre des cubes isométriques."],
  ["Fallende, gravitationssimulierte Voxel beobachten.", "Observez des voxels simulés en chute libre."],
  ["G.GAME NETZWERK BETRETEN", "ENTRER DANS LE RÉSEAU G.GAME"],
  ["GELÄNDERASTER NEU SEEDEN", "RÉINITIALISER LA GRILLE DE TERRAIN"],
  ["MALMODUS: BLÖCKE IN DER MATRIX KLICKEN", "MODE PEINTURE : CLIQUEZ SUR LES BLOCS DANS LA MATRICE"],
  ["GRAVITATIONSSIMULIERTE RENDER-PUFFER", "TAMPONS DE RENDU SIMULÉS PAR GRAVITÉ"],
  ["G.TRANS // KOGNITIVE MORPH-ENGINE", "G.TRANS // MOTEUR DE MORPH COGNITIF"],
  ["jenseits der Sprache", "au-delà de la langue"],
  [
    "Ultra-niedrige Latenz: Wir kompilieren verbale und symbolische Absicht in semantische Koordinaten und rekonstruieren Dialekte in Echtzeit.",
    "Nous exploitons un pipeline ultra-faible latence qui compile l'intention verbale et symbolique en coordonnées sémantiques standardisées avant de reconstruire les dialectes locaux en temps réel.",
  ],
  ["BEISPIELE:", "EXEMPLES SUGGÉRÉS :"],
  ["QUELLTEXT [ ENGLISCH ]", "TEXTE SOURCE [ ANGLAIS ]"],
  ["Phrase eingeben (z. B. 'Hello World')...", "Saisissez une phrase (ex. « Hello World »)..."],
  ["SYNTHESE-ZIELDIALEKT", "DIALECTE DE SORTIE SYNTHÉTISÉ"],
  ["Dialektsynthese erzwingen", "Forcer la synthèse dialectale"],
  ["ERKANNTER DIALEKT: [ {{lang}} ]", "CHAÎNE DIALECTALE LOCALISÉE : [ {{lang}} ]"],
  ["GEGENSEITIGE KORRELATION: 99,8%", "CORRÉLATION MUTUELLE : 99,8 %"],
  ["QUELLDIALEKT (EINGABE):", "DIALECTE SOURCE (ENTRÉE) :"],
  ["ZIELDIALEKT (AUSGABE):", "DIALECTE CIBLE (SORTIE) :"],
  ["SEGMENTE MORPHEN...", "MORPHING DES SEGMENTS..."],
  ["MORPH-SEQUENZ STARTEN", "LANCER LA SÉQUENCE DE MORPH"],
  ["JAPANISCH (JA)", "JAPONAIS (JA)"],
  ["DEUTSCH (DE)", "ALLEMAND (DE)"],
  ["FRANZÖSISCH (FR)", "FRANÇAIS (FR)"],
  ["SPANISCH (ES)", "ESPAGNOL (ES)"],
  ["CHINESISCH (ZH)", "CHINOIS (ZH)"],
  ["KOREANISCH (KO)", "CORÉEN (KO)"],
  ["ITALIENISCH (IT)", "ITALIEN (IT)"],
  ["G.HUB FABRIK-PIPELINE", "PROCESSUS DE PIPELINE USINE G.HUB"],
  ["GETRIEBE-LEISTUNGSGESCHWINDIGKEIT:", "VÉLOCITÉ DE PUISSANCE DU SYSTÈME D'ENGRENAGES :"],
  ["Prozessphase: {{name}}", "Phase de processus : {{name}}"],
  ["PHASEN-SPEZIFIKATIONEN:", "SPÉCIFICATIONS DE PHASE :"],
  ["ROTOREN KLICKEN FÜR FLOW-METADATEN", "CLIQUEZ SUR LES ROTORS POUR ÉTUDIER LES MÉTADONNÉES DE FLUX"],
  ["Idee", "Idée"],
  [
    "Rohe abstrakte Anforderungen in Software-Vektoren und Strukturgrenzen kristallisieren.",
    "Cristalliser des exigences abstraites brutes en vecteurs logiciels définis et limites structurelles.",
  ],
  ["Entropiefaktor: 0,12", "Facteur d'entropie : 0,12"],
  ["Synthetisierte Pipelines: aktiv", "Pipelines synthétisées : actives"],
  ["Ästhetik: Dieter Rams Minimal", "Ambiance esthétique : Dieter Rams minimal"],
  [
    "Tiefenvergleich von Tech-Stacks, Materialphysik und kognitiven Interfaces.",
    "Cartographie comparative approfondie des stacks technologiques, de la physique des matériaux et des interfaces cognitives.",
  ],
  ["Abfragetiefe: 400 Epochen", "Profondeur de requête : 400 époques"],
  ["Systemrelevanz: 98,4%", "Pertinence système : 98,4 %"],
  ["Sicherheitsvektoren: [OK]", "Vecteurs de sécurité vérifiés : [OK]"],
  [
    "Typografie, Grid-Konfigurationen und haptische Komponenten gestalten.",
    "Concevoir des systèmes typographiques impeccables, des configurations de grille et des composants haptiques.",
  ],
  ["Kontrastverhältnis: 21:1", "Rapport de contraste : 21:1"],
  ["Primärschrift: Inter", "Police principale : Inter"],
  ["Thema: Off-white slate", "Thème atmosphérique : ardoise off-white"],
  ["Prototyp", "Prototype"],
  [
    "Hochpräzise taktile Mockups und interaktive State-Controller montieren.",
    "Assembler des maquettes tactiles haute fidélité et des contrôleurs d'état interactifs.",
  ],
  ["Interaktive Treue: 100%", "Fidélité interactive : 100 %"],
  ["Loop-Latenz: < 3ms", "Latence de boucle : < 3 ms"],
  ["Audio-Klick-Synth: JA", "Synthèse de clic audio : OUI"],
  ["Entwicklung", "Développement"],
  ["Typsichere, optimierte Codebasen sauber kompilieren.", "Écrire des bases de code typées et optimisées, compilées proprement."],
  ["Runtime: Vite + SPA", "Plateforme d'exécution : Vite + SPA"],
  ["TypeScript: strict", "Couverture TypeScript : strict"],
  ["Linter: verifiziert", "État du linter : vérifié"],
  [
    "Server-Instanzen hinter Load-Balancern weltweit bereitstellen.",
    "Déployer des instances serveur indépendantes derrière des load balancers pour un accès mondial instantané.",
  ],
  ["Host: Cloud Run Edge", "Hôte : Cloud Run Edge"],
  ["CDN: Abgeschlossen", "Propagation CDN : terminée"],
  ["Produktionssysteme: 1 aktiv", "Systèmes de production actifs : 1"],
  ["PROTO-CHASSIS GESAMT: {{count}} EINHEITEN", "TOTAL CHÂSSIS PROTO : {{count}} UNITÉS"],
  ["HARDWARE-FORSCHUNGSARCHIV", "ARCHIVE DE RECHERCHE MATÉRIELLE"],
  ["Physische Form", "Assemblage"],
  ["zusammenbauen.", "de la forme physique."],
  [
    "Wir verschmelzen Software mit physischer, taktiler Mechanik — Mikrotoleranzen, Gewicht und hochperformante Interfaces.",
    "Nous fusionnons les systèmes logiciels avec une machinerie physique et tactile — micro-tolérances, poids solide et interfaces haptiques haute performance.",
  ],
  ["KARTEN KLICKEN FÜR SCHEMATIK-SPEZIFIKATIONEN", "CLIQUEZ SUR LES CARTES POUR DÉCOUVRIR LES SPÉCIFICATIONS"],
  ["SPEZIFIKATIONSZEICHNUNG: {{id}}", "DESSIN DE SPÉCIFICATION : {{id}}"],
  ["HARDWARE-KERNPARAMETER:", "PARAMÈTRES CORE MATÉRIEL :"],
  ["STATUS: IN_ENTWICKLUNG [ {{date}} ]", "STATUT : EN DÉVELOPPEMENT [ {{date}} ]"],
  ["GATEWAY-SPEZ SCHLIESSEN", "FERMER LA SPÉC PASSERELLE"],
  ["TOLERANZEN: +/- 0,05mm", "TOLÉRANCES : +/- 0,05 mm"],
  ["G.HUB PATENTE ANGEMELDET", "BREVETS G.HUB DÉPOSÉS"],
  ["Taschen-Sound-Architektur", "Architecture sonore de poche"],
  [
    "Taschengrößer physischer Synthesizer mit roher Oszillator-Wärme, federbelasteten Tasten und sofortiger Loop-Aufnahme.",
    "Synthétiseur physique de poche axé sur la chaleur d'oscillateur brute, des boutons tactiles à ressort et une capture de boucle haute fidélité immédiate.",
  ],
  ["Duale Multi-Wellen-Oszillatoren", "Oscillateurs multi-ondes doubles"],
  ["Hochfrequente Tasten", "Touches tactiles haute fréquence"],
  ["12-bit PCM Loop-Engine", "Moteur de synthèse de boucle PCM 12 bits"],
  ["Physisches Spiele-Ökosystem", "Écosystème de jeu physique"],
  [
    "Aus Aluminium gefräste Handheld-Konsole mit Low-Latency-Wireless, Custom-Raster-Silicon und prozeduralen Adaptern.",
    "Console portable usinée en aluminium avec nœuds sans fil faible latence, silicium de rendu raster personnalisé et adaptateurs de jeux procéduraux.",
  ],
  ["6061-T6 Aluminium", "Bloc en aluminium premium 6061-T6"],
  ["Voxel-Hardware-Rasterizer", "Pipeline rasteriseur matériel voxel"],
  ["120Hz micro-LED Display", "Écran micro-LED 120 Hz"],
  ["Sprach-Begleiter", "Compagnon linguistique"],
  [
    "Transparentes OLED-Reisegerät übersetzt Gespräche sofort und projiziert semantische Wortnetze auf Glas.",
    "Appareil de voyage OLED transparent traduisant instantanément les conversations et projetant des réseaux sémantiques fluides sur le verre.",
  ],
  ["Bidirektionales Transparent-Display", "Affichage transparent bidirectionnel"],
  ["Räumliches Lautsprecher-Array", "Matrice de haut-parleurs spatial omnidirectionnel"],
  ["L-05 Dialekt-Pipeline integriert", "Pipeline dialectale cognitive L-05 intégrée"],
  ["UNERFORSCHTE HORIZONTE", "HORIZONS INEXPLORÉS"],
  ["Das nächste", "La prochaine"],
  ["Experiment", "expérience"],
  ["beginnt hier.", "commence ici."],
  [
    "Räumliche Compute-Umgebung, die Layout-Gitter fließend in physische Interfaces mappt.",
    "Environnement de calcul sensoriel spatial cartographiant les grilles de disposition réelles en interfaces physiques de manière fluide.",
  ],
  [
    "Ökosystem physischer taktiler Klanggeräte aus strukturellem Aluminium.",
    "Écosystème d'appareils sonores tactiles synthétisés physiques construits en aluminium structural brut.",
  ],
  [
    "Autonome kognitive Prozesse, die Codebase-Zustände direkt interpretieren und bearbeiten.",
    "Processus logiciels cognitifs autonomes capables d'interpréter et d'éditer directement les états de la base de code.",
  ],
  ["WISSENSCHAFTLICHE ANFRAGEN SENDEN", "TRANSMETTRE DES DEMANDES SCIENTIFIQUES"],
  ["Kontakt aufnehmen", "Initier le contact"],
  [
    "Geben Sie Ihre Kommunikationsadresse ein, um sich mit Projektentwicklungen, Newsletter und Prototypen zu synchronisieren.",
    "Saisissez votre adresse de communication ci-dessous pour vous synchroniser avec nos développements de projet, mises à jour de newsletter et prototypes produits.",
  ],
  ["Ihre E-Mail wurde in G.Hub protokolliert.", "Votre adresse e-mail a été enregistrée dans G.Hub."],
  ["KOGNITIVE ADRESSE (E-MAIL):", "ADRESSE COGNITIVE (E-MAIL) :"],
  ["PROJEKTABSICHT (NACHRICHT):", "DESCRIPTION DE L'INTENTION DU PROJET (MESSAGE) :"],
  ["Systemspezifikationen oder Hardware-Updates anfragen...", "Demander des spécifications système ou des mises à jour matérielles..."],
  ["KOORDINATEN-ENVELOPE SENDEN", "TRANSMETTRE L'ENVELOPPE DE COORDONNÉES"],
  ["DATENPAKETE ÜBERTRAGEN...", "TRANSMISSION DES PAQUETS DE DONNÉES..."],
  ["VERZEICHNIS-ARCHIV", "ARCHIVE RÉPERTOIRE"],
  ["KOGNITIVE SOCIALS", "RÉSEAUX SOCIAUX COGNITIFS"],
  ["KAMMER-METADATEN-METEOROLOGIE", "MÉTÉOROLOGIE DES MÉTADONNÉES DE CHAMBRE"],
  ["KONGRUENZ-SPERRE:", "VERROUILLAGE DE CONGRUENCE :"],
  ["STABIL 99%", "STABLE 99 %"],
  ["ENGINE-METRIK:", "MÉTRIQUE MOTEUR :"],
  ["LABOR-EXPERIMENT-BEFEhle", "COMMANDES D'EXPÉRIENCE DE LABORATOIRE"],
  ["LABOR-KOGNITIVE KERNE KOLLABIERTEN", "EFFONDRER LES NOYAUX COGNITIFS DU LABORATOIRE"],
  ["Sprache", "Langue"],
  ["Ton an", "Son activé"],
  ["Ton aus", "Son désactivé"],
];

/** German → Italian replacements. */
export const deToIt = [
  ["G.Hub — Digitales Labor", "G.Hub — Laboratorio digitale"],
  ["Ton einschalten", "Attiva audio"],
  ["Ton ausschalten", "Disattiva audio"],
  ["Betriebsregister schließen", "Chiudi registro operativo"],
  ["G.HUB-MASCHINE WIEDER AKTIVIEREN", "RIATTIVA MACCHINA G.HUB"],
  [
    "Alle physischen Kammern wurden in das singuläre Koordinatensystem-Kernsegment gefaltet. Klicken Sie auf den zentralen leuchtenden Sender, um das Labor zu erweitern.",
    "Tutte le camere fisiche sono state ripiegate nel segmento centrale del sistema di coordinate. Clicca sul trasmettitore centrale illuminato per espandere il laboratorio.",
  ],
  ["G.HUB BETRIEBSREGISTER", "REGISTRO OPERATIVO G.HUB"],
  ["Ein lebendiges Erfindungsstudio", "Uno studio di invenzione vivente"],
  [
    "Willkommen bei G.Hub — einem hochpräzisen experimentellen digitalen Arbeitsraum an der Schnittstelle von visuellem Design und funktionalem Computing. Diese Plattform verbindet abstrakte Produkte (G.Game, G.Trans) in einer physischen Layout-Schleife.",
    "Benvenuto in G.Hub — uno spazio di lavoro digitale sperimentale ad alta precisione ai confini del design visivo e del computing funzionale. Questa piattaforma collega prodotti astratti (G.Game, G.Trans) in un unico loop di layout fisico.",
  ],
  ["Mechanische Navigationsanleitung", "Guida alla navigazione meccanica"],
  [
    "Jog-Dial: Permanent im linken Rand. Drehen oder ziehen, um Kammern auszuwählen.",
    "Jog dial: posizionato permanentemente nel margine sinistro. Ruota o trascina per selezionare le camere.",
  ],
  ["Mausrad: Überall scrollen, um zwischen Kammern zu wechseln.", "Rotella del mouse: scorri ovunque per passare tra le camere."],
  [
    "Indikatoren: Codes (L-01 bis L-09) stehen für Kammern im Labor-Machine-Layout.",
    "Indicatori: i codici (L-01 a L-09) rappresentano le camere nel layout della macchina del laboratorio.",
  ],
  [
    "Tastatur: Pfeiltasten (oben/unten/links/rechts) für flüssige Navigation.",
    "Tastiera: tasti freccia (su/giù/sinistra/destra) per una navigazione fluida.",
  ],
  ["KOGNITIVE BESCHLEUNIGUNG: AKTIV", "ACCELERAZIONE COGNITIVA: ATTIVA"],
  ["KRISTALLISIERTE SICHERHEIT: GESPERRT", "SICUREZZE CRISTALLIZZATE: BLOCCATE"],
  ["Wo Ideen Wirklichkeit werden", "Dove le idee diventano realtà"],
  ["Das Zusammenfügen von Gedanken visualisieren", "Visualizzare l'assemblaggio dei pensieri"],
  ["Das vernetzte neuronale Netz der Ideen", "La rete neurale connessa delle idee"],
  ["Welten schaffen, die es zu erkunden lohnt", "Creare mondi che valgono la pena esplorare"],
  ["Kommunikation jenseits der Sprache", "Comunicazione oltre la lingua"],
  ["Informationsgesteuerte Prozessmechanik", "Meccanica di processo guidata dall'informazione"],
  ["Räumlich montierte kreative Hardware", "Hardware creativa assemblata spazialmente"],
  ["Das nächste Experiment beginnt hier", "Il prossimo esperimento inizia qui"],
  ["Koordinatenparameter eingeben", "Inserisci i parametri di coordinate"],
  ["DAS LEBENDIGE DIGITALE ERFINDUNGSSTUDIO", "LO STUDIO DI INVENZIONE DIGITALE VIVENTE"],
  ["Wo Ideen Wirklichkeit werden.", "Dove le idee diventano realtà."],
  [
    "G.Hub ist ein lebendiges digitales Labor, in dem abstrakte Konzepte kristallisieren. Wir entwerfen, prototypen und bauen taktile Produkte, Kommunikations-Ökosysteme und pixelige Welten.",
    "G.Hub è un laboratorio digitale vivente dove i concetti astratti si cristallizzano. Progettiamo, prototipiamo e costruiamo prodotti tattili, ecosistemi di comunicazione e mondi pixelati.",
  ],
  ["JOG-DIAL BEDIENEN", "USA IL JOG DIAL"],
  ["DIAL DREHEN, UM NACH INNEN ZU REISEN", "GIRA IL DIAL PER VIAGGIARE VERSO L'INTERNO"],
  ["SCROLLRAD UND TOUCH-SWIPE AKTIV", "ROTELLA E SWIPE TATTILE ABILITATI"],
  ["IDEEN-EVOLUTIONS-PIPELINE", "PIPELINE DI EVOLUZIONE DELLE IDEE"],
  ["Kristallisierung", "Cristallizzazione"],
  ["abstrakter Ideenströme.", "dei flussi di idee astratte."],
  [
    "In unserem Labor durchlaufen Gedanken eine strenge automatische Kristallisation. Beobachten Sie, wie Knoten expandieren, Blueprint-Parameter fixieren und Produkte entstehen.",
    "Nel nostro laboratorio, i pensieri subiscono una rigorosa cristallizzazione automatica. Osserva i nodi espandersi, i parametri blueprint bloccarsi e i prodotti emergere.",
  ],
  ["MONTAGETIEFE WÄHLEN:", "SELEZIONA PROFONDITÀ DI ASSEMBLAGGIO:"],
  ["01. ROHE GEDANKEN", "01. PENSIERI GREZZI"],
  ["02. CAD-SKIZZEN", "02. SCHIZZE CAD"],
  ["03. VEKTOR-SCHEMATA", "03. SCHEMI VETTORIALI"],
  ["04. PRODUKTKERN", "04. NUCLEO PRODOTTO"],
  ["[STUFE KLICKEN, UM LOKALE ANZIEHUNG AUSZULÖSEN]", "[CLICCA SULLA FASE PER ATTIVARE ATTRAZIONI LOCALI]"],
  ["AUSGEWÄHLTE KAMMER-GATEWAY AKTIVIEREN", "ATTIVA GATEWAY DELLA CAMERA SELEZIONATA"],
  ["G.HUB SYSTEMVERZEICHNIS", "DIRECTORY DI SISTEMA G.HUB"],
  ["Zentraler Kern", "Nucleo centrale"],
  [
    "Innovative Spieleentwicklungsplattform, modulare Rendering-Engine und verbundenes Spieler-Ökosystem.",
    "Piattaforma innovativa di sviluppo giochi, motore di rendering modulare ed ecosistema di giocatori connessi.",
  ],
  [
    "KI-gestützte mehrsprachige Kommunikationsplattform — Dialekte in Echtzeit über Grenzen hinweg.",
    "Piattaforma di comunicazione multilingue basata su IA — dialetti fluidi in tempo reale oltre i confini.",
  ],
  [
    "Unbekannte Domänen, kinetische Architektursimulationen, räumliche Compute-Engines und KI-Module.",
    "Domini inesplorati, simulazioni di architettura cinetica, motori di compute spaziale e moduli di intelligenza.",
  ],
  ["SYSTEM-ZENTRALHUB", "HUB CENTRALE DI SISTEMA"],
  [
    "Der Zentralkern koordiniert Pipeline-Ausführung, Statusverfolgung und neuronale Datentranslation zwischen Knoten.",
    "Il nucleo centrale coordina l'esecuzione della pipeline, il tracciamento dello stato e la traduzione dei dati neurali tra i nodi.",
  ],
  ["Aktive Routing-Parameter: AKTIV", "Parametri di routing attivi: ABILITATI"],
  ["Telemetrie-Bandbreite: 10 Gb/s", "Larghezza di banda telemetria inter-nodo: 10 Gb/s"],
  ["Dezentrale Ledger-Integration: ABGESCHLOSSEN", "Integrazione ledger decentralizzato: COMPLETATA"],
  ["L-04 KREATIVE UMGEBUNG", "L-04 AMBIENTE CREATIVO"],
  [
    "G.Game ist von Grund auf für hyperreaktives Micro-Gaming, prozedurale Welten und Sandbox-Tools konzipiert.",
    "G.Game è progettato dal metallo per micro-gaming iper-reattivo, generatori di mondi procedurali e strumenti sandbox.",
  ],
  ["Render-Puffer: 120 FPS", "Velocità buffer di rendering: 120 FPS"],
  ["Physik: FULL MATRIX COMPUTE", "Parametri fisici: CALCOLO MATRICIALE COMPLETO"],
  ["Aktive Nutzer: 142.948 SECURE HUBS", "Utenti attivi: 142.948 HUB SICURI"],
  ["L-05 SPRACH-ENGINE", "L-05 MOTORE LINGUISTICO"],
  [
    "G.Trans übersetzt Intent und kognitive Sprache unter Erhalt von Ton, Kultur und Grammatikrhythmus.",
    "G.Trans traduce intento e parlato cognitivo preservando tono, riferimenti culturali e ritmo grammaticale.",
  ],
  ["Unterstützte Dialekte: 124 FLUID METAS", "Dialetti supportati: 124 META FLUIDI"],
  ["Kognitives Modell: @google/genai core pipeline", "Modello cognitivo: pipeline core @google/genai"],
  ["Transformationsdauer: < 12ms", "Durata trasformazione: < 12ms"],
  ["L-08 NÄCHSTE HORIZONTE", "L-08 PROSSIMI ORIZZONTI"],
  [
    "Sichere Sandbox für experimentelle Strukturen, autonome Agent-Pods und Multi-User-Umgebungen.",
    "Sandbox sicura che ospita strutture sperimentali reattive, pod di agenti autonomi e ambienti multi-utente.",
  ],
  ["Verfügbare Bandbreite: UNBEGRENZT", "Larghezza di banda disponibile: ILLIMITATA"],
  ["Projektstatus: AKTIVE PROTOTYPEN", "Stato progetto: PROTOTIPI ATTIVI"],
  ["Systemzustand: EVOLVIEREND", "Stato sistema: IN EVOLUZIONE"],
  ["G.GAME ÖKOSYSTEM // SANDBOX-UMGEBUNG", "ECOSISTEMA G.GAME // AMBIENTE SANDBOX"],
  ["Welten schaffen,", "Creare mondi"],
  ["die es zu erkunden lohnt.", "che valgono la pena esplorare."],
  [
    "Wir entwickeln einen modularen Spiele-Container, der Mikrophysik, dynamisches Light-Baking und isometrische prozedurale Blöcke vereinfacht.",
    "Stiamo progettando un contenitore modulare di generazione giochi che semplifica micro-fisica, light baking dinamico e mesh di blocchi procedurali isometrici.",
  ],
  ["VERFÜGBARE KONZEpte:", "OUTLINE DEI CONCETTI DISPONIBILI:"],
  ["01. ISOMETRISCHER TILE-EDITOR", "01. EDITOR TILE ISOMETRICHE"],
  ["Kacheln klicken, um isometrische Würfel zu malen.", "Clicca sulle tessere per dipingere cubi isometrici."],
  ["Fallende, gravitationssimulierte Voxel beobachten.", "Osserva voxel simulati con gravità in caduta."],
  ["G.GAME NETZWERK BETRETEN", "ENTRA NELLA RETE G.GAME"],
  ["GELÄNDERASTER NEU SEEDEN", "RIGENERA GRIGLIA TERRENO"],
  ["MALMODUS: BLÖCKE IN DER MATRIX KLICKEN", "MODALITÀ PITTURA: CLICCA I BLOCCHI NELLA MATRICE"],
  ["GRAVITATIONSSIMULIERTE RENDER-PUFFER", "BUFFER DI RENDERING SIMULATI CON GRAVITÀ"],
  ["G.TRANS // KOGNITIVE MORPH-ENGINE", "G.TRANS // MOTORE MORPH COGNITIVO"],
  ["jenseits der Sprache", "oltre la lingua"],
  [
    "Ultra-niedrige Latenz: Wir kompilieren verbale und symbolische Absicht in semantische Koordinaten und rekonstruieren Dialekte in Echtzeit.",
    "Gestiamo una pipeline a latenza ultra-bassa che compila intento verbale e simbolico in coordinate semantiche standardizzate prima di ricostruire i dialetti locali in tempo reale.",
  ],
  ["BEISPIELE:", "ESEMPI SUGGERITI:"],
  ["QUELLTEXT [ ENGLISCH ]", "TESTO SORGENTE [ INGLESE ]"],
  ["Phrase eingeben (z. B. 'Hello World')...", "Digita una frase (es. 'Hello World')..."],
  ["SYNTHESE-ZIELDIALEKT", "DIALETTO DI OUTPUT SINTETIZZATO"],
  ["Dialektsynthese erzwingen", "Forza sintesi dialettale"],
  ["ERKANNTER DIALEKT: [ {{lang}} ]", "STRINGA DIALETTO LOCALIZZATA: [ {{lang}} ]"],
  ["GEGENSEITIGE KORRELATION: 99,8%", "CORRELAZIONE MUTUA: 99,8%"],
  ["QUELLDIALEKT (EINGABE):", "DIALETTO SORGENTE (INPUT):"],
  ["ZIELDIALEKT (AUSGABE):", "DIALETTO TARGET (OUTPUT):"],
  ["SEGMENTE MORPHEN...", "MORPHING DEI SEGMENTI..."],
  ["MORPH-SEQUENZ STARTEN", "AVVIA SEQUENZA MORPH"],
  ["JAPANISCH (JA)", "GIAPPONESE (JA)"],
  ["DEUTSCH (DE)", "TEDESCO (DE)"],
  ["FRANZÖSISCH (FR)", "FRANCESE (FR)"],
  ["SPANISCH (ES)", "SPAGNOLO (ES)"],
  ["CHINESISCH (ZH)", "CINESE (ZH)"],
  ["KOREANISCH (KO)", "COREANO (KO)"],
  ["ITALIENISCH (IT)", "ITALIANO (IT)"],
  ["G.HUB FABRIK-PIPELINE", "PROCESSO PIPELINE FABBRICA G.HUB"],
  ["GETRIEBE-LEISTUNGSGESCHWINDIGKEIT:", "VELOCITÀ DI POTENZA DEL SISTEMA A INGRANAGGI:"],
  ["Prozessphase: {{name}}", "Fase di processo: {{name}}"],
  ["PHASEN-SPEZIFIKATIONEN:", "LETTURE DELLE SPECIFICHE DI FASE:"],
  ["ROTOREN KLICKEN FÜR FLOW-METADATEN", "CLICCA SUI ROTORI PER STUDIARE I METADATI DI FLUSSO"],
  ["Idee", "Idea"],
  [
    "Rohe abstrakte Anforderungen in Software-Vektoren und Strukturgrenzen kristallisieren.",
    "Cristallizzare requisiti astratti grezzi in vettori software definiti e confini strutturali.",
  ],
  ["Entropiefaktor: 0,12", "Fattore entropia: 0,12"],
  ["Synthetisierte Pipelines: aktiv", "Pipeline sintetizzate: attive"],
  ["Ästhetik: Dieter Rams Minimal", "Vibe estetica: Dieter Rams minimal"],
  [
    "Tiefenvergleich von Tech-Stacks, Materialphysik und kognitiven Interfaces.",
    "Mappatura comparativa approfondita di stack tecnologici, fisica dei materiali e interfacce cognitive.",
  ],
  ["Abfragetiefe: 400 Epochen", "Profondità query: 400 epoche"],
  ["Systemrelevanz: 98,4%", "Rilevanza sistema: 98,4%"],
  ["Sicherheitsvektoren: [OK]", "Vettori sicurezza verificati: [OK]"],
  [
    "Typografie, Grid-Konfigurationen und haptische Komponenten gestalten.",
    "Creare sistemi tipografici impeccabili, configurazioni di griglia e componenti aptici.",
  ],
  ["Kontrastverhältnis: 21:1", "Rapporto di contrasto: 21:1"],
  ["Primärschrift: Inter", "Famiglia font primaria: Inter"],
  ["Thema: Off-white slate", "Tema atmosfera: ardesia off-white"],
  ["Prototyp", "Prototipo"],
  [
    "Hochpräzise taktile Mockups und interaktive State-Controller montieren.",
    "Assemblare mockup tattili ad alta fedeltà e controller di stato interattivi.",
  ],
  ["Interaktive Treue: 100%", "Fedeltà interattiva: 100%"],
  ["Loop-Latenz: < 3ms", "Latenza risposta loop: < 3ms"],
  ["Audio-Klick-Synth: JA", "Synth click audio online: SÌ"],
  ["Entwicklung", "Sviluppo"],
  ["Typsichere, optimierte Codebasen sauber kompilieren.", "Scrivere basi di codice type-safe ottimizzate, compilate in modo pulito."],
  ["Runtime: Vite + SPA", "Piattaforma runtime: Vite + SPA"],
  ["TypeScript: strict", "Copertura TypeScript: strict"],
  ["Linter: verifiziert", "Stato linter: verificato"],
  [
    "Server-Instanzen hinter Load-Balancern weltweit bereitstellen.",
    "Avviare istanze server indipendenti dietro load balancer personalizzati per accesso mondiale istantaneo.",
  ],
  ["Host: Cloud Run Edge", "Host: Cloud Run Edge"],
  ["CDN: Abgeschlossen", "Propagazione CDN: completata"],
  ["Produktionssysteme: 1 aktiv", "Sistemi produzione attivi: 1"],
  ["PROTO-CHASSIS GESAMT: {{count}} EINHEITEN", "TOTALE CHASSIS PROTO: {{count}} UNITÀ"],
  ["HARDWARE-FORSCHUNGSARCHIV", "ARCHIVIO RICERCA HARDWARE"],
  ["Physische Form", "Assemblaggio"],
  ["zusammenbauen.", "della forma fisica."],
  [
    "Wir verschmelzen Software mit physischer, taktiler Mechanik — Mikrotoleranzen, Gewicht und hochperformante Interfaces.",
    "Uniamo sistemi software in macchinari fisici e tattili — micro-tolleranze, peso solido e interfacce aptiche ad alte prestazioni.",
  ],
  ["KARTEN KLICKEN FÜR SCHEMATIK-SPEZIFIKATIONEN", "CLICCA LE SCHEDE PER SCOPRIRE LE SPECIFICHE"],
  ["SPEZIFIKATIONSZEICHNUNG: {{id}}", "DISEGNO SPECIFICHE: {{id}}"],
  ["HARDWARE-KERNPARAMETER:", "PARAMETRI CORE HARDWARE:"],
  ["STATUS: IN_ENTWICKLUNG [ {{date}} ]", "STATO: IN SVILUPPO [ {{date}} ]"],
  ["GATEWAY-SPEZ SCHLIESSEN", "CHIUDI SPEC GATEWAY"],
  ["TOLERANZEN: +/- 0,05mm", "TOLLERANZE: +/- 0,05mm"],
  ["G.HUB PATENTE ANGEMELDET", "BREVETTI G.HUB DEPOSITATI"],
  ["Taschen-Sound-Architektur", "Architettura sonora tascabile"],
  [
    "Taschengrößer physischer Synthesizer mit roher Oszillator-Wärme, federbelasteten Tasten und sofortiger Loop-Aufnahme.",
    "Sintetizzatore fisico tascabile focalizzato sul calore dell'oscillatore grezzo, pulsanti aptici a molla e cattura loop ad alta fedeltà immediata.",
  ],
  ["Duale Multi-Wellen-Oszillatoren", "Oscillatori duali multi-onda"],
  ["Hochfrequente Tasten", "Tasti aptici ad alta frequenza"],
  ["12-bit PCM Loop-Engine", "Motore synth loop PCM 12-bit"],
  ["Physisches Spiele-Ökosystem", "Ecosistema di gioco fisico"],
  [
    "Aus Aluminium gefräste Handheld-Konsole mit Low-Latency-Wireless, Custom-Raster-Silicon und prozeduralen Adaptern.",
    "Console portatile fresata in alluminio con nodi wireless a bassa latenza, silicio raster personalizzato e adattatori di giochi procedurali.",
  ],
  ["6061-T6 Aluminium", "Slab in alluminio premium 6061-T6"],
  ["Voxel-Hardware-Rasterizer", "Pipeline rasterizer hardware voxel"],
  ["120Hz micro-LED Display", "Schermo micro-LED 120Hz"],
  ["Sprach-Begleiter", "Compagno linguistico"],
  [
    "Transparentes OLED-Reisegerät übersetzt Gespräche sofort und projiziert semantische Wortnetze auf Glas.",
    "Dispositivo da viaggio OLED completamente trasparente che traduce le conversazioni istantaneamente proiettando reti semantiche fluide sul vetro.",
  ],
  ["Bidirektionales Transparent-Display", "Display trasparente bidirezionale"],
  ["Räumliches Lautsprecher-Array", "Matrice altoparlanti spaziale omnidirezionale"],
  ["L-05 Dialekt-Pipeline integriert", "Pipeline dialettale cognitiva L-05 integrata"],
  ["UNERFORSCHTE HORIZONTE", "ORIZZONTI INESPLORATI"],
  ["Das nächste", "Il prossimo"],
  ["Experiment", "esperimento"],
  ["beginnt hier.", "inizia qui."],
  [
    "Räumliche Compute-Umgebung, die Layout-Gitter fließend in physische Interfaces mappt.",
    "Ambiente di compute sensoriale spaziale che mappa griglie di layout reali in interfacce fisiche in modo fluido.",
  ],
  [
    "Ökosystem physischer taktiler Klanggeräte aus strukturellem Aluminium.",
    "Ecosistema di dispositivi sonori tattili sintetizzati fisici costruiti con alluminio strutturale grezzo.",
  ],
  [
    "Autonome kognitive Prozesse, die Codebase-Zustände direkt interpretieren und bearbeiten.",
    "Processi software cognitivi autonomi capaci di interpretare e modificare direttamente gli stati della codebase.",
  ],
  ["WISSENSCHAFTLICHE ANFRAGEN SENDEN", "TRASMETTI RICHIESTE SCIENTIFICHE"],
  ["Kontakt aufnehmen", "Avvia contatto"],
  [
    "Geben Sie Ihre Kommunikationsadresse ein, um sich mit Projektentwicklungen, Newsletter und Prototypen zu synchronisieren.",
    "Inserisci il tuo indirizzo di comunicazione per sincronizzarti con sviluppi di progetto, newsletter e prototipi di prodotto.",
  ],
  ["Ihre E-Mail wurde in G.Hub protokolliert.", "Il tuo indirizzo email è stato registrato in G.Hub."],
  ["KOGNITIVE ADRESSE (E-MAIL):", "INDIRIZZO COGNITIVO (EMAIL):"],
  ["PROJEKTABSICHT (NACHRICHT):", "DESCRIZIONE INTENTO PROGETTO (MESSAGGIO):"],
  ["Systemspezifikationen oder Hardware-Updates anfragen...", "Richiedi specifiche di sistema o aggiornamenti hardware..."],
  ["KOORDINATEN-ENVELOPE SENDEN", "TRASMETTI BUSTA COORDINATE"],
  ["DATENPAKETE ÜBERTRAGEN...", "TRASMISSIONE PACCHETTI DATI..."],
  ["VERZEICHNIS-ARCHIV", "ARCHIVIO DIRECTORY"],
  ["KOGNITIVE SOCIALS", "SOCIAL COGNITIVI"],
  ["KAMMER-METADATEN-METEOROLOGIE", "METEOROLOGIA METADATI CAMERA"],
  ["KONGRUENZ-SPERRE:", "BLOCCO CONGRUENZA:"],
  ["STABIL 99%", "STABILE 99%"],
  ["ENGINE-METRIK:", "METRICA MOTORE:"],
  ["LABOR-EXPERIMENT-BEFEhle", "COMANDI ESPERIMENTO LABORATORIO"],
  ["LABOR-KOGNITIVE KERNE KOLLABIERTEN", "COLLASSA I NUCLEI COGNITIVI DEL LABORATORIO"],
  ["Sprache", "Lingua"],
  ["Ton an", "Audio attivo"],
  ["Ton aus", "Audio disattivo"],
];
